### PR TITLE
Adds support for Iceberg rewrite files operation

### PR DESCRIPTION
**Pull request by g-saransh**
GitHub issue link: #23 

Problem: 
Need a way to replace/rewrite iceberg data files.

Solution:
Add an option to rewrite files. The operation takes a datafile string consisting of files to be deleted (replaced) and those that should be added.

Testing:
Updated functional test.

Documentation:
Updated README file

### CODE REVIEW

**Review by s-akhtar-baig — DISMISSED** [review]

**Review by s-akhtar-baig — APPROVED** [review]

**Review by brajeshkpandey — CHANGES_REQUESTED** [review]
`rewrite` option does not make a sense ... what is the use case? may be there is a valid usecase

**Comment by g-saransh** [comment]
> `rewrite` option does not make a sense ... what is the use case? may be there is a valid usecase

Rewrite option can be used when we want to changes data files without changing the actual data. This option allows the user to atomically replace the data file path(s). Some of the scenarios that can use this option:
1. Split larger data file(s) into smaller files
2. Combine smaller data files into bigger file(s)
3. Move data files from one location to another

**Review by mderoy — APPROVED** [review]
lgtm

**Review by brajeshkpandey — APPROVED** [review]
@g-saransh ok,  I would have used delete and write methods but I am ok with rewrite also.

**Pull request merged**
